# This is a basic workflow to help you get started with Actions

name:  Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: harrylu99/blog@master
      env:
        ACCESS_TOKEN: ${{ secrets.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 }}
        TARGET_REPO: harrylu99/blog
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://www.xxx.com


# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#    steps:
#     - name: Checkout
#       uses: actions/checkout@master

#     - name: vuepress-deploy
#       uses: harrylu99/blog@master
#       env:
#         ACCESS_TOKEN: ${{ secrets.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 }}
#         TARGET_REPO: harrylu99/blog
#         TARGET_BRANCH: master
#         BUILD_SCRIPT: yarn && yarn build
#         BUILD_DIR: docs/.vuepress/dist

#       # 运行构建脚本
#       - name: Build VuePress site
#         run: yarn docs:build

#       # 查看 workflow 的文档来获取更多信息
#       # @see https://github.com/crazy-max/ghaction-github-pages
#       - name: Deploy to GitHub Pages
#         uses: crazy-max/ghaction-github-pages@v2
#         with:
#           # 部署到 gh-pages 分支
#           target_branch: gh-pages
#           # 部署目录为 VuePress 的默认输出目录
#           build_dir: docs/.vuepress/dist
#         env:
#           # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
#           GITHUB_TOKEN: ${{ secrets.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 }}
